name: Build Minecraft Mod

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -lah
          find . -maxdepth 3 \( -name "gradlew" -o -name "build.gradle*" -o -name "settings.gradle*" \)

      - name: Install Java 25
        run: |
          apt-get update
          apt-get install -y curl ca-certificates gnupg
          curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /usr/share/keyrings/adoptium.gpg
          echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb bookworm main" > /etc/apt/sources.list.d/adoptium.list
          apt-get update
          apt-get install -y temurin-25-jdk

      - name: Show Java version
        run: java -version

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: List jars
        run: ls -lah build/libs

      - name: Upload jar artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: minecraft-mod-jar.zip
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar