modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="atsassistmod"
version="1.8.0"
displayName="ATSA"
authors="325"
description='''ATS assist utilities for RealTrainModRenewed. Requires RealTrainModRenewed.'''

[[dependencies.atsassistmod]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atsassistmod]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.atsassistmod]]
    modId="realtrainmodrenewed"
    type="required"
    versionRange="[0.0.0,)"
    ordering="AFTER"
    side="BOTH"
